# Colors
text_color: "" # Omitted configs are fine, will use defaults/terminal colors

# bg_color: "" # Missing a field is also fine, will use defauls/terminal colors
even_square_color: "#1C2B1C"
odd_square_color: "#263726"
selected_color: "#FF0000"
# border_color: ""

# Chars
flag_char: "F"
mine_char: "X"
